name: Build project
on: [push, workflow_dispatch]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Get code
                uses: actions/checkout@v3
            -   name: Install NodeJs
                uses: actions/setup-node@v3
                with:
                    node-version: 18
            -   name: Cache dependencies
                uses: actions/cache@v3
                with:
                    path: ~/.npm
                    key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
            -   name: Install dependencies
                run: npm ci
            -   name: Build project
                run: npm run build
            -   name: Echo status
                run: echo 'Build completed successfully.'

